POST https://new-calcula-tu-compra.herokuapp.com/users/login
Content-Type: application/json

{
  "username": "juan",
  "password": "12345"
}

###

POST http://localhost:3000/users/create
Content-Type: application/json

{
  "username": "juan",
  "password": "12345"
}

### 
GET https://new-calcula-tu-compra.herokuapp.com/products/categories


### 
GET http://localhost:3000/products/categories/3


### 
GET http://localhost:3000/products/page/1

### 
GET http://localhost:3000/products/search/hacendado/page/1

### 
GET http://localhost:3000/products/categoryid/1/page/1

###
POST http://localhost:3000/lists/create
Content-Type: application/json
Authorization: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjUsImV4cGlyZSI6MTYxMTU5OTQ5OSwiaWF0IjoxNjExNTk4ODk5fQ.D_d68Dt3oISdq3O03KYH4Qfmfd084URzjNBgbIqPGl8"

{
  "title": "juans list",
  "userid": "5",
  "products": [1,1,1,1,1,1,3,5,5,5]
}


###
POST https://new-calcula-tu-compra.herokuapp.com/lists/last
Content-Type: application/json
Authorization:"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjUsImV4cGlyZSI6MTYxMjU0MTYyNywiaWF0IjoxNjExNjc3NjI3fQ.Q9HlDxvd8EOmxQ7xRrV7XGvg7DDfmJpLgha0IHsoVl0"

{
   "userid": "5"
}

###
POST  http://localhost:3000/lists/favorite
Content-Type: application/json
Authorization: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjUsImV4cGlyZSI6MTYxMjU0MTYyNywiaWF0IjoxNjExNjc3NjI3fQ.Q9HlDxvd8EOmxQ7xRrV7XGvg7DDfmJpLgha0IHsoVl0"

{
  "userid": "5"
}

###
POST http://localhost:3000/profile/
Content-Type: application/json
Authorization: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjUsImV4cGlyZSI6MTYxMTY4NjgxNiwiaWF0IjoxNjExNjg2MjE2fQ.h0-oI9I08Ob7fn306lUBP1oz9rzgGGmNY3gynF_1Ttg"

{
  "userid": "5"
}


###
POST http://localhost:3000/profile/avatar
Content-Type:  application/json
Authorization: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjUsImV4cGlyZSI6MTYxMTY4NjgxNiwiaWF0IjoxNjExNjg2MjE2fQ.h0-oI9I08Ob7fn306lUBP1oz9rzgGGmNY3gynF_1Ttg"

{
  "userid": "5",
  "avatarUrl": "https://i.pinimg.com/originals/b0/45/9a/b0459ad3f7c2159032f24da9e40a9ec9.jpg"
}


###
POST  http://localhost:3000/profile/newfavorite
Content-Type: application/json
Authorization: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjUsImV4cGlyZSI6MTYxMjU1MDk3MiwiaWF0IjoxNjExNjg2OTcyfQ.L9HmDuqUn2rFbwyKXjTmKqW4Eu5mRYwe1VeROVPm2xM"

{
  "userid": "5",
  "listId": "8"
}

###
POST  http://localhost:3000/profile/removefavorite
Content-Type: application/json
Authorization: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjUsImV4cGlyZSI6MTYxMjU1MDk3MiwiaWF0IjoxNjExNjg2OTcyfQ.L9HmDuqUn2rFbwyKXjTmKqW4Eu5mRYwe1VeROVPm2xM"

{
  "userid": "5"
}


###
POST  http://localhost:3000/profile/search
Content-Type: application/json
Authorization: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjUsImV4cGlyZSI6MTYxMjU1MDk3MiwiaWF0IjoxNjExNjg2OTcyfQ.L9HmDuqUn2rFbwyKXjTmKqW4Eu5mRYwe1VeROVPm2xM"

{
  "userid": "5",
  "searchText": "mi Lista"
}


###
POST  http://localhost:3000/profile/getsearchedlist
Content-Type: application/json
Authorization: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjUsImV4cGlyZSI6MTYxMjU1MDk3MiwiaWF0IjoxNjExNjg2OTcyfQ.L9HmDuqUn2rFbwyKXjTmKqW4Eu5mRYwe1VeROVPm2xM"

{
  "userid": "5",
  "listId": 5
}


###
POST  http://localhost:3000/profile/listdaterange
Content-Type: application/json
Authorization: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjUsImV4cGlyZSI6MTYxMjU1MDk3MiwiaWF0IjoxNjExNjg2OTcyfQ.L9HmDuqUn2rFbwyKXjTmKqW4Eu5mRYwe1VeROVPm2xM"

{
  "userid": "5",
  "dateFrom": "2021/01/01",
  "dateTo": "2021/01/26"
}

###
POST  http://localhost:3000/profile/stats
Content-Type: application/json
Authorization: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjUsImV4cGlyZSI6MTYxMjU1MDk3MiwiaWF0IjoxNjExNjg2OTcyfQ.L9HmDuqUn2rFbwyKXjTmKqW4Eu5mRYwe1VeROVPm2xM"

{
  "userid": "5"
}


